name: Docs

on:
  push:
    branches:
    - main
    paths:
    - src/**
    - poehali/**
    - .github/workflows/main.yml
  pull_request:
    branches:
    - main
    paths:
    - poehali/**
    - .github/workflows/main.yml
  workflow_dispatch:

jobs:
  generate-docs:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup DocFX
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx

    - name: DocFX Build
      working-directory: poehali
      run: docfx .\docfx.json
      continue-on-error: false

    - name: Publish
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: poehali/_site
        force_orphan: true
